# ==========================
# BiffyBot Configuration - Biffy Clyro Discord Server
# ==========================

# --------------------------
# Status Messages
# --------------------------
# Status messages to rotate through for the bot's presence.

statuses:
  - "Mountains ğŸ”º"
  - "Many of Horror ğŸ’”"
  - "Bubbles ğŸ’¦"
  - "Black Chandelier ğŸ•¯ï¸"
  - "Biblical âœï¸"
  - "The Captain âš“"
  - "Rearrange ğŸ”€"
  - "Wolves of Winter ğŸº"
  - "God & Satan âš–ï¸"
  - "Opposite â†”ï¸"
  - "That Golden Rule ğŸ©¸"
  - "Machines ğŸ› ï¸"
  - "Victory Over the Sun ğŸŒ‘"
  - "Flammable ğŸ”¥"
  - "Folding Stars âœ¨"
  - "Stingin' Belle ğŸ¦‚"
  - "57 ğŸšï¸"
  - "Joy.Discovery.Invention âš¡"
  - "A Hunger in Your Haunt ğŸŒ«ï¸"
  - "Instant History â±ï¸"
  - "The Joke's On Us ğŸ­"
  - "Saturday Superhouse ğŸšï¸"
  - "Who's Got a Match? ğŸ”¥"
  - "Glitter and Trauma ğŸ’¥"
  - "The Thaw â„ï¸"
  - "Questions and Answers â“"

# --------------------------
# Channel and Role IDs
# --------------------------
# IDs of channels and roles used by the bot for various functions.

liveshows_channel_id: 1380157321547874414              # Forum channel for live shows threads.
welcome_channel_id: 1380157415097634868        # Channel where welcome messages are posted.
new_member_channel_id: 1380157745851793408        # Channel where new members are directed.
dm_forward_channel_id: 1380176986512822324    # Channel for forwarding direct messages.
instagram_announce_channel_id: 1380157930233397359  # Discord channel ID for announcements.
instagram_ping_role_id: 1380175070101770321 # The role to ping when there's a new post.

# --------------------------
# Feature Toggles
# --------------------------
# Enable or disable specific features. Set to 'true' to enable the feature.
welcome_enabled: true     # Set to true to enable welcome messages.

# --------------------------
# Instagram Settings
# --------------------------
instagram_username: biffy_clyro
instagram_poll_interval: 300   # seconds between checks.
