# ==========================
# SigridHQ Configuration - Sigrid Discord Server
# ==========================

# --------------------------
# Status Messages
# --------------------------
# Status messages to rotate through for the bot's presence.

statuses:
  - "Strangers ğŸ¤"
  - "Don't Kill My Vibe âœ‹"
  - "Sucker Punch ğŸ¥Š"
  - "Plot Twist ğŸ“š"
  - "Mirror ğŸª"
  - "Don't Feel Like Crying ğŸ˜¢"
  - "High Five ğŸ™Œ"
  - "Burning Bridges ğŸ”¥"
  - "It Gets Dark ğŸŒ‘"
  - "Bad Life ğŸ’”"
  - "Head on Fire ğŸ”¥ğŸ§ "
  - "Sight of You ğŸ‘€"
  - "Dynamite ğŸ’£"
  - "Basic âšª"
  - "Home to You ğŸ "
  - "Maybe It's a Good Thing âœ…"
  - "Raw ğŸ¤"
  - "Level Up â¬†ï¸"
  - "Schedules ğŸ—“ï¸"
  - "Focus ğŸ¯"
  - "Dance for Me ğŸ’ƒ"
  - "In Vain ğŸŒ€"
  - "A Driver Saved My Night ğŸš—"
  - "Ring ğŸ’"

# --------------------------
# Channel and Role IDs
# --------------------------
# IDs of channels and roles used by the bot for various functions.

liveshows_channel_id: 1380157321547874414              # Forum channel for live shows threads.
welcome_channel_id: 1380157415097634868        # Channel where welcome messages are posted.
new_member_channel_id: 1380157745851793408        # Channel where new members are directed.
dm_forward_channel_id: 1380176986512822324    # Channel for forwarding direct messages.
instagram_announce_channel_id: 1380157930233397359  # Discord channel ID for announcements.
instagram_ping_role_id: 1380175070101770321 # The role to ping when there's a new post.

# --------------------------
# Feature Toggles
# --------------------------
# Enable or disable specific features. Set to 'true' to enable the feature.
welcome_enabled: true     # Set to true to enable welcome messages.

# --------------------------
# Instagram Settings
# --------------------------
instagram_username: thisissigrid
instagram_poll_interval: 300   # seconds between checks.
